items = [
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('ch', 'Chinese'),
    ('ko', 'Korean'),
    ('ja', 'Japanese'),
    ('be', 'Belarus'),
    ('sp', 'Spanish'),
    ('it', 'Italian'),
    ('po', 'Polish'),
    ('pr', 'Portugese'),
    ('sw', 'Sweden'),
    ('fi', 'Finland'),
    ('no', 'Norway'),
    ('ir', 'Irish'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français')
]


lexicon = {
    'en': 'English',
    'ge': 'Deutsch',
    'fr': 'Français',
    'ch': 'Chinese',
    'ko': 'Korean',
    'ja': 'Japanese',
    'be': 'Belarus',
    'sp': 'Spanish',
    'it': 'Italian',
    'po': 'Polish',
    'pr': 'Portugese',
    'sw': 'Sweden',
    'fi': 'Finland',
    'no': 'Norway',
    'ir': 'Irish',
}
