items = [
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('ch', '中國人'),
    ('ko', '한국인'),
    ('ja', '日本語'),
    ('be', 'Беларускі'),
    ('sp', 'Español'),
    ('it', 'Italiano'),
    ('po', 'Polski'),
    ('pr', 'Português'),
    ('sw', 'Svenska'),
    ('fi', 'Suomalainen'),
    ('no', 'Norsk'),
    ('ir', 'Gaeilge'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français')
]


lexicon = {
    'en': 'English',
    'ge': 'Deutsch',
    'fr': 'Français',
    'ch': '中國人',
    'ko': '한국인',
    'ja': '日本語',
    'be': 'Беларускі',
    'sp': 'Español',
    'it': 'Italiano',
    'po': 'Polski',
    'pr': 'Português',
    'sw': 'Svenska',
    'fi': 'Suomalainen',
    'no': 'Norsk',
    'ir': 'Gaeilge',
}
