items = [
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français'),
    ('en', 'English'),
    ('ge', 'Deutsch'),
    ('fr', 'Français')
]


lexicon = {
    'en': 'English',
    'ge': 'Deutsch',
    'fr': 'Français'
}
